### ISSUE TITLE
[Bug]: Adding a task in the markdown view doesn't update the Kannan board view

### ISSUE THREAD

**Issue by anandrajaram** [mgmeyers/obsidian-kanban#380] opened 2021-11-12 19:47 UTC
### Describe the bug

When I add tasks in the underlying Markdown file (text) and then switch to the board view, the changes are not reflected in the board view. The change still exists when I switch back to the Markdown view. 

### Expected Behavior

Editing Markdown view should update the board view

### Steps to reproduce

Open a kanban board
Switch to Markdown view via "Open as Markdown"
Add a task to any of the lists in the markdown file
Switching to Board view. 
The new task should be visible in the board view. 

### Operating system

macOS

**Comment by Joshfairhead** [comment] 2021-11-12 23:07
Same for issue for me. I have some additional behaviour to add to the previous comment though. Switching between two kanbans, the plugin got confused and duplicated the info of one. The markdown was also duplicated across notes.

**Comment by mgmeyers** [comment] 2021-11-21 18:03
So, several people have reported this issue now, but I haven't been able to reproduce it yet. The next time it happens, could you open up the developer console to see if there are any errors? It's `command + option + i` on mac and `ctrl + shift + i` on windows.

They'll look something like this:
<img width="629" alt="Screen Shot 2021-11-21 at 9 57 10 AM" src="https://user-images.githubusercontent.com/2694747/142773557-b1172ba5-17a6-485e-80c9-0cccdf5436bb.png">

**Comment by mgmeyers** [comment] 2021-11-21 19:23
@anandrajaram & @Joshfairhead Can you update the plugin and see if you still run into these issues? I've made some updates that I hope address what's going on here.

**Comment by anandrajaram** [comment] 2021-11-22 02:27
Thank you @mgmeyers . After updating the plugin, I don't seem to be having the issue any more. I did a few quick tests, and will report back if I run into it again in everyday use. Thanks again.

**Comment by ljavuras** [comment] 2021-11-30 21:37
> Same for issue for me. I have some additional behaviour to add to the previous comment though. Switching between two kanbans, the plugin got confused and duplicated the info of one. The markdown was also duplicated across notes.

Also encountered this bug recently, haven't happened again after I reload Obsidian.

**Comment by OogieM** [comment] 2021-12-04 14:09
I have this issue as well, opened the console and the only this odd that is showing is
 ```DevTools failed to load SourceMap: Could not load content for app://obsidian.md/main.js.map:```

**Comment by mgmeyers** [comment] 2021-12-04 17:54
@OogieM Does this happen consistently for you, or just occasionally?

**Comment by OogieM** [comment] 2021-12-04 18:37
Only occasionally. But it has happened in every one of the kanban board notes I have made at least once.  It and the missing cards are somehow related. Once I get this error I will almost certainly get the unable to add cards error soonish but not immediately.

**Comment by Daeik** [comment] 2021-12-11 04:13
It happens to me too time to time. (Using Obsidian `v0.12.19` with Obsidian Kanban `v1.2.22`)

I'm not sure what triggers this particular issue, but I'm assuming that **raw markdown file change events aren't properly caught and synced back to Kanban view states** in reported cases.

- "Open as Markdown" and editing `.md` file via Obsidian editor doesn't sync the file content changes back to Kanban view ([as mentioned above](https://github.com/mgmeyers/obsidian-kanban/issues/380#issue-1052359881))
- [In Obsidian Dataview Plugin's TASK views](https://blacksmithgu.github.io/obsidian-dataview/query/queries/#task-queries), if I tick a task's checkbox in a kanban board(`.md`), the checkbox's state change does persist in the raw `.md` file but Kanban view doesn't reflect the change.

**Comment by mgmeyers** [comment] 2022-01-15 19:10
Thanks for this @zhao414. The issues with renaming a kanban board should be fixed now. It surfaced a small bug that may have caused the original issue in this thread, but I'm not sure. @anandrajaram @OogieM @Daeik @ljavuras let me know if you still encounter issues switching between kanban and markdown modes.

**Comment by OogieM** [comment] 2022-01-16 01:23
OK I'll do some testing starting tomorrow. I've been only using my kanban boards in either kanban or markdown and restarting Obsidian in between switching which may have aleviated the problem.

**Comment by mgmeyers** [comment] 2022-03-30 18:47
Hey all, I'm wondering if any of you have run into this issue lately? I think I may have fixed it a while back, but because I wasn't able to reproduce, I'm not sure. Let me know!

**Comment by zhao414** [comment] 2022-03-31 05:40
For me, I didn't run into this issue any more, thanks.

**Comment by OogieM** [comment] 2022-03-31 13:30
Once I switched the default operation to finish a card by hitting enter I haven't had the problem. I almost wonder if one issue is if I have a not yet finished card and then go back and forth? Didn't really try that yet. But in any case no more issues.

**Closed** 2022-04-02 18:50 UTC
Labels: bug, help wanted, needs investigation
