### ISSUE TITLE
Card groups like in Notion

### ISSUE THREAD

**Issue by AB1908** [mgmeyers/obsidian-kanban#514] opened 2022-04-13 08:51 UTC
### Goal or desired outcome of this feature

When managing tasks for a project, I find that I break down tasks by feature/functional area. I have a list of tasks I want to tackle and seeing them grouped by feature would help give me a sense of how much work I have to do. I found that this is possible in Notion:
![image](https://user-images.githubusercontent.com/14124383/163138020-2173d295-dac8-4021-b60d-ddce488dec7f.png)

Here, you can see card groups defined by a metadata field called "Feature".

### Describe the feature

Create card groups by using a metadata field as depicted in screenshot.

### Can you think of any alternatives or work-arounds?

Arrange them manually?

**Comment by laurastephsmith** [comment] 2022-04-29 20:56
Is this a version of swimlanes?
![kanban-board-with-swimlanes](https://user-images.githubusercontent.com/16104950/166068067-9e076e6e-dd7b-4308-a347-0e690a767e30.jpg)

**Comment by AB1908** [comment] 2022-04-29 23:23
Aye that seems to be most similar. TBH I really liked kabmat and taskell but I can't do this kind of metadata organization so I've fallen back to Obsidian. I imagine this is a ways off since I want to use Dataview queries to populate this list here (see #345).

**Comment by laurastephsmith** [comment] 2022-04-30 21:13
Same, can't wait for the dataview feature!

**Comment by skyue** [comment] 2022-05-22 13:29
i like this.

maybe use H2 title as column, H3 title as group in column.

now i create a special card to divided cards into different groups.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/10450242/169697387-47d7c6d0-e247-4cb1-ae51-2c4da35436a0.png">

**Comment by mgmeyers** [comment] 2022-06-25 23:48
Thanks @AB1908 closing this issue as a duplicate of #237

**Closed by mgmeyers** 2022-06-25 23:48 UTC
Labels: enhancement

**Comment by AvMavs** [comment] 2023-01-22 05:33
I know this is closed as completed, but I can't figure out how to use the feature?

(I'm on the latest version of both Obsidian and Kanban)

**Comment by AB1908** [comment] 2023-01-23 13:07
@AvMavs subscribe to 237.
