### ISSUE TITLE
Error message "invariant failed"

### ISSUE THREAD

**Issue by hauselin** [mgmeyers/obsidian-kanban#178] opened 2021-06-09 04:55 UTC
Hi, thanks for making this incredible plugin!

I've been using it for a few days and have run into this problem a few times. Occasionally (happens 1-2 times a day), I can't drag cards around. Just now, when that happened, I tried to view the note as a markdown file in edit mode. Then, instead of seeing the markdown text, I see this error instead: `Something went wrong. Invariant failed` (I don't see any error messages in the console though). Each time it happened, reloading Obsidian fixed the problem.

**Comment by mgmeyers** [comment] 2021-06-09 05:15
Thanks @hauselin. Could you tell me more about what you're doing when this happens? Are you dragging between different boards, or within a single board?

**Comment by hauselin** [comment] 2021-06-09 05:28
I'm dragging cards within a single board. 

It's hard to pin down what exactly I was doing when each time it happened. If I remember correctly, most of the time, I probably editing a card before that. I'll try to make a note when this happens again. I'll post it here. Thanks again!

**Comment by pjeby** [comment] 2021-06-10 00:43
Tip for anyone trying to reproduce this problem: a large board (w/200-250 items, lots of images), open in two panes side-by-side will frequently do it, just keep dragging stuff (even within one board).  The most recent message for me was "Cannot find droppable entry with id [xxxxx]".

I *think* that the issues I'm seeing are due to timing and rendering problems.  Specifically, using two copies of the same board means that the inactive view reparses after every save, causing a re-render (due to changes in ids), causing re-layout/re-flow at the browser level), and that there are timing issues as a result.  Oftentimes there will be a lag between grabbing an item and it actually moving, and when that happens the invariant failure is more likely.

My guess is that, in order to fix the issue, the parser needs to be able to reproduce droppable ids (and therefore react item keys) between different revisions of a file.  Say, for example, that parsing produced a cache mapping line strings to card instances (including identity), and the same for unparsing the state back to a file.  Then, whenever the file needs to be parsed because of an external change, then (assuming it's the same file) the parser can look up already-parsed task lines from the cache and use them.  (It's slightly more complicated than that, due to possible duplicate lines.)

The result would be faster update of the view, since most IDs would not change, so react wouldn't force redraw and browser re-layout.  A similar thing could be done by replacing the unique ID with a content hash made from the text of the line and the count of how many times that line has been seen in the file while parsing.

After some experiments, I found that the parser is insanely slow, taking >1ms per line, which means that it takes a quarter second just to parse a board with a few hundred items.  After fiddling around with the parsing machinery to do some caching, I managed to cut that down to almost zero after a board is loaded -- under 1ms to parse a changed version of a file that's already been loaded, because it only processes lane headers and changed lines.

But it still takes *seconds* for the display to update from that, which makes me think there's gotta be something going on with the change reconciliation that's forcing large parts of the display to update in spite of everything I did to make the items properly keyable.

After even more experiments, I found some issues with how data bridging is done -- among other things, the useEffect setup is such that a setInternal is often done in *direct response* to a setExternal...  which really shouldn't happen, because it basically means it's scheduling outward saves and the like for no reason, to overwrite with the same (or sometimes *different*!) data.  That is, I've managed to catch it changing *back* something that had been changed externally, e.g.:

* File is saved in other window, triggering setExternal
* setExternal fires setBoardData on React
* React schedules re-render of the board
* Re-render checks the useEffect, sees boardData has changed, and sends it back out to setInternal

With some fiddling between these various things, and figuring out a bunch of other places where the file or internal state can be corrupted, I have been able to get my local copy to *almost* be able to keep up with me typing in a second window, on that really large board.  (On sufficiently-small boards, it can keep up.)

There seems to be some significant costs involved in rendering individual cards; removing a large number of cards is much faster than adding them.  I haven't yet investigated where that's coming from.  But in the meantime, I think I'm going to try to clean up the logic and speed fixes I've done and post a PR.  I'm also going to see if I can figure out why errors aren't going away any more when you change the state externally.  (Probably won't have it done for a few days, though.)

Roughly, the plan is:

* Review and verify all the state logic issues I've come across, and clean up my quick-fixes, add types, comments, etc.
* Retest doing lots of drag-and-reorg on the same board I first had problems with, to see whether there's any improvement
* Investigate rendering performance to see what's taking it so darn long

I'm guessing that once we can use scrolling lanes, we'll be able to improve rendering speed a lot by using virtual lists; that should avoid dom re-layout for changes that happen off-screen.  Obsidian makes extensive use of virtualization to improve its components' speed, and once scrolling is taken care of we can do the same.

**Comment by mgmeyers** [comment] 2021-06-10 01:51
Thanks for all your work on this @pjeby, this is exciting stuff!

I'd put my money on `MarkdownRenderer` as a major source of performance issues. The flow for that looks like:

1. Create dom element
2. Convert markdown string to HTML and render into that element
3. Convert element BACK to string so it can be used in `dangerouslySetInnerHTML`

I tried some more performant approaches using refs, but that resulted in flickering when dragging items and lanes around. Maybe there's another approach, though?

Additionally, there's a lot of memoization that could be done to prevent unnecessary updates. For example:

- Context values
- `draggableLaneFactory` / `draggableItemFactory` <-- I feel like these need to be rethought entirely, but probably after switching DnD libs
- `renderLanes`
- `LaneItems`
- Several event handlers


I was hoping to switch dnd libraries before doing any major perf updates, because I imagine that will require some refactoring anyway. But it seems like figuring some of this out now would be worthwhile.

**Comment by mgmeyers** [comment] 2021-06-10 02:23
@pjeby another thought I just had. Do you think switching to Preact could have caused any of these issues / any perf issues? No clue on my end, but I'd be curious to profile them side-by-side.

**Comment by pjeby** [comment] 2021-06-10 05:42
So far, every performance problem I've been identified has been squarely the fault of the plugin.  (Some my code, some yours.)

Some of them have been due to refreshing when it wasn't necessary (my refreshViews thing was the completely wrong way to do it), or because the data bridge setup was wrong (dueling useEffect+useState).  The thing I'm tracking down now is that *just* the component rendering for my test board takes like 300ms -- and that's *not* doing any markdown rendering.  (Though that takes ~2ms per line, or half a second for the whole board when everything starts up.)

That time is 100% in the plugin's .tsx files, creating the shadow DOM, *not* in preact or browser rendering, so there's still a bunch of work to be done to rule stuff out.  The shadow dom creation for each item is another 2ms or so.

A *lot* of this would go away in a virtualized list (ala Trello) situation because you'd not render offscreen items, even for dom diffing.  But in this case, it's clear there's a ton of overhead in the components themselves.

I do wonder about the dangerouslySetInnerHTML...  but a quick test of taking it out shows that the markdown rendering isn't the bottleneck.  It's still ~2ms per item, meaning all the overhead is coming from other parts of the Item.

It's possible this has to do with the event handlers: https://ntsim.uk/posts/optimizing-react-component-event-handlers -- I'm going to investigate that next.  In general, it looks like there is a metric f-ton of objects and closures that get created, and it all happens in the closure from draggableItemFactory.  About 3/4 of the pure "re-render the board" time (not counting DOM reflow) is spent there, which I verified by replacing it with a function to return a div with a few letters in it, in place of the full item.

Okay, so a whole bunch of time is spent uselessly memoizing precreated menus, instead of creating them on the fly as needed.  That's another big chunk if fixed.  But that's still only 1/4 of the time off, basically.

I'm still investigating, but my gut feel at this point is that the components are not really designed to work well in a reactive way.  There is way too much stuff getting passed down from the top into every little component, and too many closures being created everywhere.

Anyway, the state logic definitely needs fixing, and the parsing and caching tricks I've come up with fix a lot of other stuff, but the big chunks of time are still in all the render code, and the fact that the *entire* board is being re-rendered for every keypress (the plugin code re-rendering, not the preact/HTML part), due to insufficiently clean props.  (which causes child components to be re-rendered unnecessarily).  At this point, I'm not sure how much of that is actually react-beautiful-dnd's fault, vs how much is the fact that the entire *board* is being passed down to every item, instead of only that item (and lanes for the lanes, etc.).  I'm pretty sure that the reason redux exists is to let you just pass down local data as props, and then have a global way to say things like "update this item".

**Comment by pjeby** [comment] 2021-06-10 09:16
Update: I've figured out how to fix all of the state logic and most of the rendering logic.  There were some really hairy interactions between how Obsidian wants to update the file-related state, and the way the databridge was hooked into things, etc. etc.  I *think* I've now got them all working in such a way that they don't loop back on themselves, except for the Obsidian parts that at least detect when they're looping back on themselves.  :grimacing:

Whether it will fix the "invariant failed" message generally, I don't know, but so far I haven't had any of those yet.  On the other hand, I haven't been doing most of my testing with the really big board yet.  I'll do that tomorrow, after separating performance changes from logic fixes (so I can fully stress test it).  But with the smaller boards and just viewing the larger one, I haven't had any problems.  Anyway, if all that works out then I'll commit the perf changes as well.

I think there's room for some absolutely huge improvements in update-rendering performance even without going virtual, though.  The key is to make it so that the JSX bits being returned from component functions are *exactly* the same as their previous version if nothing needs to change.  (Where exactly means not just equivalent functions, but the *same* function instances.)  Some significant refactoring may be required for that, though.

What I've learned from today is that what you really want, if at all possible, is to be either 1) sending state-setting messages to the leaf-most components that you possibly can, or 2) make darn sure that all your JSX returns don't change in *any* way if there's not really anything different.  (In which case, it's almost like sending a message to just the bit that changed, with only a small amount of overhead.)  Anyway, given that most changes only affect a small part of the board, there's definitely room for improvement.

Initial load time for boards will still be high, though, unless there's some work that can be done to speed up the parser, and the markdown -> HTML conversion.  I have some ideas for both, but they're not really low-hanging fruit like caching parsed lines was.

**Comment by mgmeyers** [comment] 2021-06-10 16:22
Awesome! This is all helpful info you've uncovered. I have some ideas on how to refactor everything, but I think I'll wait on that until we choose a new DnD library. That'll be a good time to do both. I'll add perf improvements to the roadmap

**Comment by hauselin** [comment] 2021-06-10 18:49
Fantastic! Thanks for working on it. Just sponsored the project—maybe @mgmeyers can split the $ with @pjeby ;)

**Comment by pjeby** [comment] 2021-06-10 19:21
Nah, he's done the bulk of the work making this happen.  My pay is getting the features I need.  (And learning react is a side bonus.)

**Comment by pjeby** [comment] 2021-06-11 05:16
Okay, after my most recent commits on #190, I did a bunch of sorting of my large board (lots of drag-drop, plus editing a side-by-side text mode version) and was unable to produce any glitches of any kind.  (Granted, I'm actually using a version with some performance enhancements and stable item IDs, but all the changes I made that were *intended* to fix all the weird error potentials and corner cases are now part of #190.)

**Comment by mgmeyers** [comment] 2021-06-17 23:05
Hey @hauselin I haven't been able to reproduce this issue after the latest rounds of updates. Going to close this for now, but let me know if you're still having issues.

**Closed by mgmeyers** 2021-06-17 23:05 UTC
