### ISSUE TITLE
[Bug]: Drag and Drop in pop-out window does not work. 

### ISSUE THREAD

**Issue by paulsp** [mgmeyers/obsidian-kanban#556] opened 2022-06-17 20:25 UTC
### Describe the bug

Obsidian 0.15.1
Kanban Plug-in 1.2.40
Dragging and cards in Kanban board that is in pop out windows does not work. Specifically the card is hard to pickup and cannot be dropped in a list.

### Expected Behavior

In a pop out window:
- Grab a card
- Move the card to a different list
- Drop the card.

### Steps to reproduce

This is the expected behavior.  You may be able to grab the card, but it can not be dropped.

In a pop out window:
- Grab a card
- Move the card to a different list
- Drop the card.

### Operating system

macOS

**Comment by pjeby** [comment] 2022-06-18 06:51
Duplicate of #552

**Closed** 2022-06-27 23:35 UTC
Labels: bug, verified, unreleased-fix
