### ISSUE TITLE
[Bug]: Date Display Color

### ISSUE THREAD

**Issue by esilbe1** [mgmeyers/obsidian-kanban#1045] opened 2024-09-03 21:50 UTC
### Describe the bug

I am using the Kaban plug-in and discovered the Date Display Color. I was able to change it to change the color of dates past the current date. I'm trying to do the same for dates before the "due" date, but I can't get it to work. I want anything before the date on the card to be green.
<img width="758" alt="Screenshot_2024-09-02_at_9 06 51_PM" src="https://github.com/user-attachments/assets/c292d0ef-4fce-4208-9530-d7c4811639ec">

### Expected Behavior

The date tag on the Kaban board card should change color when this setting is changed. 

### Steps to reproduce

Open Kaban Board Settings 
Scroll to dat display color setting 
Change settings as pictured

### Operating system

macOS

**Comment by HaBiX02** [comment] 2024-09-08 18:03
Hello there, i think it is not a Bug of the program itself, but rather of your specification.
You have a rule that says:
' If Date is before now then is yellow ' and then another one is ' if Date is before now and 1 month before, then green'.
I think the program reads the specifications top to bottom, so the first one that matches is the yellow rule.
If you try to delete that last 'yellow' rule you could potentially fix it.

**Comment by esilbe1** [comment] 2024-09-17 15:48
Thanks, this did the trick!

**Comment by HaBiX02** [comment] 2024-09-19 14:52
Nice!, I am happy that it works, now as the problem is fixed, if you could close the issue it would be greatly appreciated :D

**Comment by esilbe1** [comment] 2024-09-19 15:11
This resolved my issue.

**Closed** 2024-09-19 15:11 UTC
Labels: bug
