### ISSUE TITLE
[Feature]: Multiple list lanes

### ISSUE THREAD

**Issue by firinael** [mgmeyers/obsidian-kanban#539] opened 2022-05-17 19:38 UTC
### Goal or desired outcome of this feature

Being able to create groups of lists without having to create multiple boards and split the view.

### Describe the feature

More than 1 list of cards per column. Basically, this:

![Screenshot 2022-05-17 163050](https://user-images.githubusercontent.com/67032657/168895039-0d9f9d2d-4790-4799-8672-d06773b52915.jpg)

Or maybe this:

![Screenshot 2022-05-17 163050](https://user-images.githubusercontent.com/67032657/168895867-04ae84a9-621b-455a-aba5-a2641473e64a.jpg)

(sorry for the shitty mockups)

**Comment by mgmeyers** [comment] 2022-06-25 23:58
Thanks @firinael! Closing this as a duplicate of #237

**Closed by mgmeyers** 2022-06-25 23:58 UTC
Labels: enhancement
